import PySimpleGUI as sg


class Test_window:
    def __init__(self, givenTheme, configObject):
        sg.theme(givenTheme)
        self.configObject = configObject
        self.testLayout = self.setup_test_layout()

    def setup_test_layout(self):
        testLayout = [[sg.Text("Current stage: ", size=(int(675 / 12), 1), font="Comic 12 bold")],
                      [sg.Text("List of stages:", size=(int(675 / 8), 1), font="Comic 8 bold")],
                      [sg.Listbox(values=[], size=(int(675 / 16), 15), key="LIST-STAGES",
                                  enable_events=True, select_mode="SELECT_MODE_SINGLE")],
                      [sg.Text("Files generated by stage:", size=(int(675 / 8), 1), font="Comic 8 bold")],
                      [sg.Listbox(values=[], size=(int(675 / 16), 15), key="LIST-FILES",
                                  enable_events=True, select_mode="SELECT_MODE_SINGLE")],
                      [sg.T("Process the next stage: ", size=(int(675 / 8), 1), font="Comic 8 bold")],
                      [sg.Button("NEXT", enable_events=True, key="BUTTON-NEXT", size=(10, 1))]]
        outputCoumn = [[sg.Text("Selected file display: ", size=(int(675 / 12), 1), font="Comic 12 bold")],
                       [sg.Image(key="IMAGE-SHOWN", size=(500, 888), background_color="black")]]

        constructed_Window = [[sg.Column(testLayout), sg.VSeparator(), sg.Column(outputCoumn)]]
        return constructed_Window

    def getFirstWindow(self):
        startLayout = self.setup_test_layout()
        window = sg.Window('Window Title', layout=startLayout, margins=(0, 0), size=(1200, 675))
        return window
